# Generated by Django 3.2 on 2022-05-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_weoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weoffer',
            name='content',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='weoffer',
            name='image',
            field=models.ImageField(upload_to='weoffer'),
        ),
    ]
