# Generated by Django 3.2 on 2022-05-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20220525_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery')),
                ('title', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('according', models.CharField(choices=[('month', 'month'), ('year', 'year')], max_length=100)),
            ],
        ),
    ]
