# Generated by Django 3.2 on 2022-05-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project')),
                ('price', models.FloatField()),
                ('according', models.CharField(choices=[('month', 'month'), ('year', 'year')], max_length=100)),
                ('street_location', models.CharField(max_length=500)),
            ],
        ),
    ]
