# Generated by Django 3.2 on 2022-05-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default='fffggg', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(default='ny', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='street_location',
            field=models.CharField(max_length=200),
        ),
    ]
