# Generated by Django 3.2 on 2022-05-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20220525_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ourteam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ourteam')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
